### ISSUE TITLE
Multiple Package Installation

### ISSUE THREAD

**Issue by michaelkornblum** [devisle/advanced-react-cli#30]
It would be great if you were able to pick and choose what modules you would like to install with react all in one go. For example, let's say that I wanted React with React-Router, Redux and Material Components, I'd be able to select those modules from a list of checkboxes and the app would install them.

Also a status bar that tracks the progress of module installation would do wonders for the user experience.

**Comment by endormi** [comment]
Thanks for this feature request! @shreyas1307 will most likely look into this, but if he doesn't have time I will.

**Comment by shreyas1307** [comment]
Will get onto working the multiple-package installation soon. Should be able to release it hopefully by Sunday.

**Comment by endormi** [comment]
This issue was fixed with #31
